name: Keep Vercel Functions Warm

on:
  schedule:
    - cron: '*/3 * * * *' # every 3 minutes

jobs:
  keep-warm:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Vercel Endpoint
        run: curl -s -o /dev/null https://neighbourly-backend.vercel.app
